[package]
name = "skyless_systems_core"
version = "0.0.1"
edition = "2021"

[dependencies]
skyless_core = { path = "../../core" }

bytes = "1.5.0"
futures = "0.3.30"
itertools = "0.12.1"
num_enum = "0.7.2"
openssl = "0.10.63"
tokio = "1.36.0"
tokio-util = "0.7.10"
