FROM rust:alpine

RUN apk -U upgrade
RUN apk add --no-cache musl-dev openssl-dev

WORKDIR /skyless
COPY . .

RUN cargo install cargo-watch
ENV RUSTFLAGS=-Ctarget-feature=-crt-static

CMD ["cargo", "watch", "-x", "run"]
