[package]
name = "skyless_macros"
version = "0.0.1"
authors = ["bpawel10"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.4.0"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "1.0.76", features = ["parsing"] }
